// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfHt-iexL4bBgE1J6nGxtZd5prKxrRI3s',
    appId: '1:69207647544:web:e1db6ae7b0c282d2eb0dcd',
    messagingSenderId: '69207647544',
    projectId: 'taskapp-3fbec',
    authDomain: 'taskapp-3fbec.firebaseapp.com',
    storageBucket: 'taskapp-3fbec.appspot.com',
    measurementId: 'G-28Z6XYT7NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa0G_qQX8xRanAgiZtdvIiqOCTf0-julQ',
    appId: '1:69207647544:android:52a32a3ec2de2289eb0dcd',
    messagingSenderId: '69207647544',
    projectId: 'taskapp-3fbec',
    storageBucket: 'taskapp-3fbec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2jPlWyesJXty53Vedw-9bYVWhSMko-dk',
    appId: '1:69207647544:ios:3c72760c780477dceb0dcd',
    messagingSenderId: '69207647544',
    projectId: 'taskapp-3fbec',
    storageBucket: 'taskapp-3fbec.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2jPlWyesJXty53Vedw-9bYVWhSMko-dk',
    appId: '1:69207647544:ios:3c72760c780477dceb0dcd',
    messagingSenderId: '69207647544',
    projectId: 'taskapp-3fbec',
    storageBucket: 'taskapp-3fbec.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );
}
